apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "real-estate-backend.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "real-estate-backend.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.backend.env.springProfile | quote }}
  SERVER_PORT: {{ .Values.backend.env.serverPort | quote }}
  DB_HOST: {{ include "real-estate-backend.postgresql.serviceName" . }}
  DB_PORT: {{ .Values.postgresql.service.port | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.backend.env.corsAllowedOrigins | quote }}
