apiVersion: v1
kind: Secret
metadata:
  name: {{ include "real-estate-backend.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "real-estate-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DB_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
  {{- else }}
  DB_USER: {{ .Values.backend.env.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.backend.env.dbPassword | b64enc | quote }}
  {{- end }}
