apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kong.name }}-config
  namespace: {{ .Values.namespace.name }}
data:
  KONG_DATABASE: "{{ .Values.kong.env.database }}"
  KONG_PG_HOST: "{{ .Values.kong.env.pgHost }}"
  KONG_PG_PORT: "{{ .Values.kong.env.pgPort }}"
  KONG_PG_DATABASE: "{{ .Values.kong.env.pgDatabase }}"
  KONG_PG_USER: "{{ .Values.kong.env.pgUser }}"
  KONG_PROXY_ACCESS_LOG: "{{ .Values.kong.env.proxyAccessLog }}"
  KONG_ADMIN_ACCESS_LOG: "{{ .Values.kong.env.adminAccessLog }}"
  KONG_PROXY_ERROR_LOG: "{{ .Values.kong.env.proxyErrorLog }}"
  KONG_ADMIN_ERROR_LOG: "{{ .Values.kong.env.adminErrorLog }}"
  KONG_ADMIN_LISTEN: "0.0.0.0:{{ .Values.kong.admin.httpPort }}"
  KONG_PROXY_LISTEN: "0.0.0.0:{{ .Values.kong.proxy.httpPort }}"
  KONG_PLUGINS: "{{ .Values.kong.env.plugins }}"
