apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kong.name }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  KONG_PG_PASSWORD: "{{ .Values.kong.env.pgPassword }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password }}"
