apiVersion: v1
kind: ConfigMap
metadata:
  name: real-estate-backend-config
  namespace: real-estate
  labels:
    app: real-estate-backend
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8080"
  DB_HOST: "real-estate-backend-postgres"
  DB_PORT: "5432"
  DB_NAME: "realestatedb"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3001"
