-- Seed script for 100 mock properties
-- Run this manually after initial migration: psql -U postgres -d realestatedb -f seed_properties.sql
-- Or in your SQL client

-- Insert 100 properties with realistic Vietnamese real estate data
INSERT INTO properties (title, description, price, address, city, bedrooms, bathrooms, area, property_type, status, user_id, created_at, updated_at) VALUES
('Villa 1 tại Hà Nội', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 32500000000, '456 Nguyễn Huệ, Hà Nội', 'Hà Nội', 5, 4, 380, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
('Căn hộ 2 tại TP. Hồ Chí Minh', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 14500000, '789 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 2, 1, 85, 'APARTMENT', 'FOR_RENT', 'user-2', NOW() - INTERVAL '28 days', NOW() - INTERVAL '28 days'),
('Nhà phố 3 tại Đà Nẵng', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 7200000000, '123 Trần Phú, Đà Nẵng', 'Đà Nẵng', 4, 3, 180, 'TOWNHOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '42 days', NOW() - INTERVAL '42 days'),
('Biệt thự 4 tại Hải Phòng', 'Biệt thự hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 28000000000, '567 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 6, 4, 420, 'VILLA', 'FOR_SALE', 'user-2', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('Nhà ở 5 tại Cần Thơ', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 38000000, '234 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 3, 2, 120, 'HOUSE', 'FOR_RENT', 'user-1', NOW() - INTERVAL '67 days', NOW() - INTERVAL '67 days'),
('Chung cư 6 tại Nha Trang', 'Chung cư hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 3800000000, '890 Hoàng Diệu, Nha Trang', 'Nha Trang', 2, 2, 95, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('Villa 7 tại Vũng Tàu', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 185000000, '456 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 4, 3, 280, 'VILLA', 'FOR_RENT', 'user-1', NOW() - INTERVAL '89 days', NOW() - INTERVAL '89 days'),
('Penthouse 8 tại Huế', 'Penthouse hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 5500000000, '123 Võ Thị Sáu, Huế', 'Huế', 3, 2, 150, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '34 days', NOW() - INTERVAL '34 days'),
('Duplex 9 tại Biên Hòa', 'Duplex hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 12500000000, '789 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 5, 3, 220, 'TOWNHOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '56 days', NOW() - INTERVAL '56 days'),
('Villa 10 tại Thủ Đức', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 45000000000, '234 Lê Duẩn, Thủ Đức', 'Thủ Đức', 6, 5, 450, 'VILLA', 'FOR_SALE', 'user-2', NOW() - INTERVAL '78 days', NOW() - INTERVAL '78 days'),
('Nhà phố 11 tại Hà Nội', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 8900000000, '567 Nguyễn Huệ, Hà Nội', 'Hà Nội', 4, 3, 175, 'TOWNHOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '23 days', NOW() - INTERVAL '23 days'),
('Căn hộ 12 tại TP. Hồ Chí Minh', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 2300000000, '890 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 1, 1, 65, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '91 days', NOW() - INTERVAL '91 days'),
('Villa 13 tại Đà Nẵng', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 38500000000, '123 Trần Phú, Đà Nẵng', 'Đà Nẵng', 5, 4, 390, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('Nhà ở 14 tại Hải Phòng', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 5700000000, '456 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 3, 2, 140, 'HOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '45 days', NOW() - INTERVAL '45 days'),
('Nhà phố 15 tại Cần Thơ', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 58000000, '789 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 4, 3, 185, 'TOWNHOUSE', 'FOR_RENT', 'user-1', NOW() - INTERVAL '62 days', NOW() - INTERVAL '62 days'),
('Căn hộ 16 tại Nha Trang', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 1800000000, '234 Hoàng Diệu, Nha Trang', 'Nha Trang', 2, 1, 70, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
('Villa 17 tại Vũng Tàu', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 41000000000, '567 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 6, 4, 430, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '71 days', NOW() - INTERVAL '71 days'),
('Biệt thự 18 tại Huế', 'Biệt thự hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 125000000, '890 Võ Thị Sáu, Huế', 'Huế', 4, 3, 310, 'VILLA', 'FOR_RENT', 'user-2', NOW() - INTERVAL '36 days', NOW() - INTERVAL '36 days'),
('Nhà ở 19 tại Biên Hòa', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 4200000000, '123 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 2, 2, 110, 'HOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '52 days', NOW() - INTERVAL '52 days'),
('Nhà phố 20 tại Thủ Đức', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 10500000000, '456 Lê Duẩn, Thủ Đức', 'Thủ Đức', 5, 3, 200, 'TOWNHOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
('Căn hộ 21 tại Hà Nội', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 3500000000, '789 Nguyễn Huệ, Hà Nội', 'Hà Nội', 3, 2, 105, 'APARTMENT', 'FOR_SALE', 'user-1', NOW() - INTERVAL '88 days', NOW() - INTERVAL '88 days'),
('Villa 22 tại TP. Hồ Chí Minh', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 215000000, '234 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 5, 4, 350, 'VILLA', 'FOR_RENT', 'user-2', NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
('Nhà phố 23 tại Đà Nẵng', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 11200000000, '567 Trần Phú, Đà Nẵng', 'Đà Nẵng', 4, 3, 190, 'TOWNHOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '47 days', NOW() - INTERVAL '47 days'),
('Chung cư 24 tại Hải Phòng', 'Chung cư hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 2700000000, '890 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 2, 2, 80, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '25 days', NOW() - INTERVAL '25 days'),
('Villa 25 tại Cần Thơ', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 30000000000, '123 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 5, 4, 370, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '69 days', NOW() - INTERVAL '69 days'),
('Nhà ở 26 tại Nha Trang', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 6800000000, '456 Hoàng Diệu, Nha Trang', 'Nha Trang', 3, 2, 155, 'HOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
('Nhà phố 27 tại Vũng Tàu', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 48500000, '789 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 4, 3, 170, 'TOWNHOUSE', 'FOR_RENT', 'user-1', NOW() - INTERVAL '81 days', NOW() - INTERVAL '81 days'),
('Căn hộ 28 tại Huế', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 4200000000, '234 Võ Thị Sáu, Huế', 'Huế', 3, 2, 120, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '39 days', NOW() - INTERVAL '39 days'),
('Villa 29 tại Biên Hòa', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 35500000000, '567 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 6, 5, 410, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '58 days', NOW() - INTERVAL '58 days'),
('Penthouse 30 tại Thủ Đức', 'Penthouse hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 170000000, '890 Lê Duẩn, Thủ Đức', 'Thủ Đức', 4, 3, 240, 'APARTMENT', 'FOR_RENT', 'user-2', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
('Nhà ở 31 tại Hà Nội', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 5200000000, '123 Nguyễn Huệ, Hà Nội', 'Hà Nội', 3, 2, 130, 'HOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '73 days', NOW() - INTERVAL '73 days'),
('Nhà phố 32 tại TP. Hồ Chí Minh', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 9800000000, '456 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 4, 3, 195, 'TOWNHOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days'),
('Căn hộ 33 tại Đà Nẵng', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 1500000000, '789 Trần Phú, Đà Nẵng', 'Đà Nẵng', 1, 1, 55, 'APARTMENT', 'FOR_SALE', 'user-1', NOW() - INTERVAL '95 days', NOW() - INTERVAL '95 days'),
('Villa 34 tại Hải Phòng', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 42000000000, '234 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 6, 4, 440, 'VILLA', 'FOR_SALE', 'user-2', NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days'),
('Biệt thự 35 tại Cần Thơ', 'Biệt thự hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 198000000, '567 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 5, 4, 320, 'VILLA', 'FOR_RENT', 'user-1', NOW() - INTERVAL '54 days', NOW() - INTERVAL '54 days'),
('Nhà ở 36 tại Nha Trang', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 3900000000, '890 Hoàng Diệu, Nha Trang', 'Nha Trang', 2, 2, 95, 'HOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
('Nhà phố 37 tại Vũng Tàu', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 13500000000, '123 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 5, 3, 210, 'TOWNHOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '64 days', NOW() - INTERVAL '64 days'),
('Căn hộ 38 tại Huế', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 22000000, '456 Võ Thị Sáu, Huế', 'Huế', 2, 1, 75, 'APARTMENT', 'FOR_RENT', 'user-2', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
('Villa 39 tại Biên Hòa', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 26500000000, '789 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 5, 4, 360, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '43 days', NOW() - INTERVAL '43 days'),
('Duplex 40 tại Thủ Đức', 'Duplex hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 4800000000, '234 Lê Duẩn, Thủ Đức', 'Thủ Đức', 3, 2, 135, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '76 days', NOW() - INTERVAL '76 days'),
('Nhà ở 41 tại Hà Nội', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 7500000000, '567 Nguyễn Huệ, Hà Nội', 'Hà Nội', 4, 3, 165, 'HOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '27 days', NOW() - INTERVAL '27 days'),
('Nhà phố 42 tại TP. Hồ Chí Minh', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 65000000, '890 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 4, 3, 180, 'TOWNHOUSE', 'FOR_RENT', 'user-2', NOW() - INTERVAL '50 days', NOW() - INTERVAL '50 days'),
('Căn hộ 43 tại Đà Nẵng', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 3200000000, '123 Trần Phú, Đà Nẵng', 'Đà Nẵng', 2, 2, 90, 'APARTMENT', 'FOR_SALE', 'user-1', NOW() - INTERVAL '85 days', NOW() - INTERVAL '85 days'),
('Villa 44 tại Hải Phòng', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 39500000000, '456 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 6, 5, 425, 'VILLA', 'FOR_SALE', 'user-2', NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days'),
('Nhà ở 45 tại Cần Thơ', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 6200000000, '789 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 3, 2, 145, 'HOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '61 days', NOW() - INTERVAL '61 days'),
('Nhà phố 46 tại Nha Trang', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 11800000000, '234 Hoàng Diệu, Nha Trang', 'Nha Trang', 5, 3, 205, 'TOWNHOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '37 days', NOW() - INTERVAL '37 days'),
('Căn hộ 47 tại Vũng Tàu', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 18500000, '567 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 1, 1, 60, 'APARTMENT', 'FOR_RENT', 'user-1', NOW() - INTERVAL '70 days', NOW() - INTERVAL '70 days'),
('Villa 48 tại Huế', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 33000000000, '890 Võ Thị Sáu, Huế', 'Huế', 5, 4, 375, 'VILLA', 'FOR_SALE', 'user-2', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
('Biệt thự 49 tại Biên Hòa', 'Biệt thự hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 165000000, '123 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 4, 3, 290, 'VILLA', 'FOR_RENT', 'user-1', NOW() - INTERVAL '48 days', NOW() - INTERVAL '48 days'),
('Nhà ở 50 tại Thủ Đức', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 8900000000, '456 Lê Duẩn, Thủ Đức', 'Thủ Đức', 4, 3, 175, 'HOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '83 days', NOW() - INTERVAL '83 days'),
('Nhà phố 51 tại Hà Nội', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 14200000000, '789 Nguyễn Huệ, Hà Nội', 'Hà Nội', 5, 3, 215, 'TOWNHOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
('Căn hộ 52 tại TP. Hồ Chí Minh', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 2100000000, '234 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 2, 1, 72, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '55 days', NOW() - INTERVAL '55 days'),
('Villa 53 tại Đà Nẵng', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 240000000, '567 Trần Phú, Đà Nẵng', 'Đà Nẵng', 5, 4, 385, 'VILLA', 'FOR_RENT', 'user-1', NOW() - INTERVAL '31 days', NOW() - INTERVAL '31 days'),
('Nhà ở 54 tại Hải Phòng', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 4700000000, '890 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 2, 2, 115, 'HOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '66 days', NOW() - INTERVAL '66 days'),
('Nhà phố 55 tại Cần Thơ', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 10200000000, '123 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 4, 3, 195, 'TOWNHOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '40 days', NOW() - INTERVAL '40 days'),
('Căn hộ 56 tại Nha Trang', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 3700000000, '456 Hoàng Diệu, Nha Trang', 'Nha Trang', 3, 2, 110, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
('Villa 57 tại Vũng Tàu', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 44000000000, '789 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 6, 4, 455, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '74 days', NOW() - INTERVAL '74 days'),
('Penthouse 58 tại Huế', 'Penthouse hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 28500000, '234 Võ Thị Sáu, Huế', 'Huế', 2, 1, 90, 'APARTMENT', 'FOR_RENT', 'user-2', NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days'),
('Nhà ở 59 tại Biên Hòa', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 5800000000, '567 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 3, 2, 140, 'HOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '59 days', NOW() - INTERVAL '59 days'),
('Nhà phố 60 tại Thủ Đức', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 12800000000, '890 Lê Duẩn, Thủ Đức', 'Thủ Đức', 5, 3, 208, 'TOWNHOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '93 days', NOW() - INTERVAL '93 days'),
('Căn hộ 61 tại Hà Nội', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 1600000000, '123 Nguyễn Huệ, Hà Nội', 'Hà Nội', 1, 1, 58, 'APARTMENT', 'FOR_SALE', 'user-1', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('Villa 62 tại TP. Hồ Chí Minh', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 29500000000, '456 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 5, 4, 365, 'VILLA', 'FOR_SALE', 'user-2', NOW() - INTERVAL '46 days', NOW() - INTERVAL '46 days'),
('Biệt thự 63 tại Đà Nẵng', 'Biệt thự hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 152000000, '789 Trần Phú, Đà Nẵng', 'Đà Nẵng', 4, 3, 300, 'VILLA', 'FOR_RENT', 'user-1', NOW() - INTERVAL '77 days', NOW() - INTERVAL '77 days'),
('Nhà ở 64 tại Hải Phòng', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 7100000000, '234 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 4, 3, 160, 'HOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '24 days', NOW() - INTERVAL '24 days'),
('Nhà phố 65 tại Cần Thơ', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 55000000, '567 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 4, 3, 185, 'TOWNHOUSE', 'FOR_RENT', 'user-1', NOW() - INTERVAL '51 days', NOW() - INTERVAL '51 days'),
('Căn hộ 66 tại Nha Trang', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 4500000000, '890 Hoàng Diệu, Nha Trang', 'Nha Trang', 3, 2, 125, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '87 days', NOW() - INTERVAL '87 days'),
('Villa 67 tại Vũng Tàu', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 36500000000, '123 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 5, 4, 395, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
('Duplex 68 tại Huế', 'Duplex hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 5100000000, '456 Võ Thị Sáu, Huế', 'Huế', 3, 2, 140, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '35 days', NOW() - INTERVAL '35 days'),
('Villa 69 tại Biên Hòa', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 48000000000, '789 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 6, 5, 470, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '68 days', NOW() - INTERVAL '68 days'),
('Penthouse 70 tại Thủ Đức', 'Penthouse hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 42500000, '234 Lê Duẩn, Thủ Đức', 'Thủ Đức', 2, 1, 98, 'APARTMENT', 'FOR_RENT', 'user-2', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
('Nhà ở 71 tại Hà Nội', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 6500000000, '567 Nguyễn Huệ, Hà Nội', 'Hà Nội', 3, 2, 148, 'HOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '53 days', NOW() - INTERVAL '53 days'),
('Nhà phố 72 tại TP. Hồ Chí Minh', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 9500000000, '890 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 4, 3, 192, 'TOWNHOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '86 days', NOW() - INTERVAL '86 days'),
('Căn hộ 73 tại Đà Nẵng', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 12500000, '123 Trần Phú, Đà Nẵng', 'Đà Nẵng', 1, 1, 62, 'APARTMENT', 'FOR_RENT', 'user-1', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),
('Villa 74 tại Hải Phòng', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 31500000000, '456 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 5, 4, 372, 'VILLA', 'FOR_SALE', 'user-2', NOW() - INTERVAL '41 days', NOW() - INTERVAL '41 days'),
('Biệt thự 75 tại Cần Thơ', 'Biệt thự hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 205000000, '789 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 5, 4, 335, 'VILLA', 'FOR_RENT', 'user-1', NOW() - INTERVAL '75 days', NOW() - INTERVAL '75 days'),
('Nhà ở 76 tại Nha Trang', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 8200000000, '234 Hoàng Diệu, Nha Trang', 'Nha Trang', 4, 3, 170, 'HOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '26 days', NOW() - INTERVAL '26 days'),
('Nhà phố 77 tại Vũng Tàu', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 14800000000, '567 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 5, 3, 218, 'TOWNHOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '60 days', NOW() - INTERVAL '60 days'),
('Căn hộ 78 tại Huế', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 2900000000, '890 Võ Thị Sáu, Huế', 'Huế', 2, 2, 88, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '94 days', NOW() - INTERVAL '94 days'),
('Villa 79 tại Biên Hòa', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 37500000000, '123 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 6, 4, 415, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('Duplex 80 tại Thủ Đức', 'Duplex hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 35500000, '456 Lê Duẩn, Thủ Đức', 'Thủ Đức', 2, 1, 105, 'APARTMENT', 'FOR_RENT', 'user-2', NOW() - INTERVAL '49 days', NOW() - INTERVAL '49 days'),
('Nhà ở 81 tại Hà Nội', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 9200000000, '789 Nguyễn Huệ, Hà Nội', 'Hà Nội', 4, 3, 182, 'HOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '82 days', NOW() - INTERVAL '82 days'),
('Nhà phố 82 tại TP. Hồ Chí Minh', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 13100000000, '234 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 5, 3, 212, 'TOWNHOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '32 days', NOW() - INTERVAL '32 days'),
('Căn hộ 83 tại Đà Nẵng', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 3100000000, '567 Trần Phú, Đà Nẵng', 'Đà Nẵng', 2, 2, 92, 'APARTMENT', 'FOR_SALE', 'user-1', NOW() - INTERVAL '65 days', NOW() - INTERVAL '65 days'),
('Villa 84 tại Hải Phòng', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 192000000, '890 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 4, 3, 325, 'VILLA', 'FOR_RENT', 'user-2', NOW() - INTERVAL '90 days', NOW() - INTERVAL '90 days'),
('Nhà ở 85 tại Cần Thơ', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 5400000000, '123 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 3, 2, 135, 'HOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '38 days', NOW() - INTERVAL '38 days'),
('Nhà phố 86 tại Nha Trang', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 10700000000, '456 Hoàng Diệu, Nha Trang', 'Nha Trang', 4, 3, 198, 'TOWNHOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '72 days', NOW() - INTERVAL '72 days'),
('Căn hộ 87 tại Vũng Tàu', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 4100000000, '789 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 3, 2, 115, 'APARTMENT', 'FOR_SALE', 'user-1', NOW() - INTERVAL '29 days', NOW() - INTERVAL '29 days'),
('Villa 88 tại Huế', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 225000000, '234 Võ Thị Sáu, Huế', 'Huế', 5, 4, 380, 'VILLA', 'FOR_RENT', 'user-2', NOW() - INTERVAL '57 days', NOW() - INTERVAL '57 days'),
('Biệt thự 89 tại Biên Hòa', 'Biệt thự hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 40500000000, '567 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 6, 5, 435, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '92 days', NOW() - INTERVAL '92 days'),
('Nhà ở 90 tại Thủ Đức', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 7800000000, '890 Lê Duẩn, Thủ Đức', 'Thủ Đức', 3, 2, 162, 'HOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '44 days', NOW() - INTERVAL '44 days'),
('Nhà phố 91 tại Hà Nội', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 71000000, '123 Nguyễn Huệ, Hà Nội', 'Hà Nội', 5, 3, 205, 'TOWNHOUSE', 'FOR_RENT', 'user-1', NOW() - INTERVAL '80 days', NOW() - INTERVAL '80 days'),
('Căn hộ 92 tại TP. Hồ Chí Minh', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 2500000000, '456 Lê Lợi, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', 2, 1, 78, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '33 days', NOW() - INTERVAL '33 days'),
('Villa 93 tại Đà Nẵng', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 34000000000, '789 Trần Phú, Đà Nẵng', 'Đà Nẵng', 5, 4, 385, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '63 days', NOW() - INTERVAL '63 days'),
('Nhà ở 94 tại Hải Phòng', 'Nhà ở hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 6900000000, '234 Hai Bà Trưng, Hải Phòng', 'Hải Phòng', 4, 3, 158, 'HOUSE', 'FOR_SALE', 'user-2', NOW() - INTERVAL '96 days', NOW() - INTERVAL '96 days'),
('Nhà phố 95 tại Cần Thơ', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 12200000000, '567 Lý Thường Kiệt, Cần Thơ', 'Cần Thơ', 5, 3, 207, 'TOWNHOUSE', 'FOR_SALE', 'user-1', NOW() - INTERVAL '79 days', NOW() - INTERVAL '79 days'),
('Căn hộ 96 tại Nha Trang', 'Căn hộ hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 19500000, '890 Hoàng Diệu, Nha Trang', 'Nha Trang', 1, 1, 67, 'APARTMENT', 'FOR_RENT', 'user-2', NOW() - INTERVAL '84 days', NOW() - INTERVAL '84 days'),
('Villa 97 tại Vũng Tàu', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 46500000000, '123 Phan Đình Phùng, Vũng Tàu', 'Vũng Tàu', 6, 5, 465, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '97 days', NOW() - INTERVAL '97 days'),
('Penthouse 98 tại Huế', 'Penthouse hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 5300000000, '456 Võ Thị Sáu, Huế', 'Huế', 3, 2, 145, 'APARTMENT', 'FOR_SALE', 'user-2', NOW() - INTERVAL '98 days', NOW() - INTERVAL '98 days'),
('Villa 99 tại Biên Hòa', 'Villa hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 27500000000, '789 Nguyễn Văn Linh, Biên Hòa', 'Biên Hòa', 5, 4, 368, 'VILLA', 'FOR_SALE', 'user-1', NOW() - INTERVAL '99 days', NOW() - INTERVAL '99 days'),
('Nhà phố 100 tại Thủ Đức', 'Nhà phố hiện đại, thiết kế sang trọng, nội thất cao cấp. Vị trí đắc địa, gần trung tâm thành phố, tiện ích đầy đủ. Không gian sống thoáng mát, an ninh tốt, phù hợp cho gia đình hoặc đầu tư.', 62500000, '234 Lê Duẩn, Thủ Đức', 'Thủ Đức', 4, 3, 188, 'TOWNHOUSE', 'FOR_RENT', 'user-2', NOW() - INTERVAL '100 days', NOW() - INTERVAL '100 days');

-- Insert property images (5 images per property)
INSERT INTO property_images (property_id, image_url)
SELECT p.id, '/images/properties/property-' || p.id || '-' || s.img_num || '.jpg'
FROM properties p
CROSS JOIN (SELECT generate_series(1, 5) AS img_num) s
WHERE p.id <= 100;

-- Insert property features (2-5 random features per property)
INSERT INTO property_features (property_id, feature)
SELECT p.id, f.feature
FROM properties p
CROSS JOIN LATERAL (
  SELECT feature
  FROM unnest(ARRAY['Bãi đậu xe', 'Sân vườn', 'Hồ bơi', 'Phòng gym', 'An ninh 24/7',
                    'Thang máy', 'Sân thượng', 'Ban công', 'Phòng giặt', 'Phòng làm việc'])
  AS feature
  ORDER BY random()
  LIMIT floor(random() * 4 + 2)::int
) f
WHERE p.id <= 100;

-- Summary
SELECT 'Properties inserted: ' || COUNT(*) FROM properties;
SELECT 'Property images inserted: ' || COUNT(*) FROM property_images;
SELECT 'Property features inserted: ' || COUNT(*) FROM property_features;
