{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "real-estate-backend.fullname" . }}-backend-pvc
  namespace: {{.Values.namespace.name }}
  labels:
    {{- include "real-estate-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
