apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authService.name }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.authService.env.dbUser }}"
  DB_PASSWORD: "{{ .Values.authService.env.dbPassword }}"
