apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authService.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.authService.name }}
spec:
  type: {{ .Values.authService.service.type }}
  ports:
    - port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.authService.service.type "NodePort") .Values.authService.service.nodePort }}
      nodePort: {{ .Values.authService.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.authService.name }}
