apiVersion: v1
kind: Secret
metadata:
  name: {{ include "post-service.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "post-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.postService.env.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postService.env.dbPassword | b64enc | quote }}
